services:
  server:
    env_file: .env
    container_name: eb_alb_rds
    image: 905418339132.dkr.ecr.us-east-1.amazonaws.com/bia:4050d20
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
